### PR TITLE
Sending out changes in a serial background queue

### PR DESCRIPTION
**Pull request by artman**
Merging to branch "threads" in order to keep development stable

### CODE REVIEW

**Comment by robskillington** [comment]
Interesting, definitely a big speedup for the TransactionTest by a factor of 2x+.  90ms vs roughly 210ms.  We should probably increase some of the loop counts for the other tests as they show up as 6ms and 14ms respectively which is hard to measure change over time.  

I think we'll need to do a bunch more refactoring to make this change unfortunately.  Adding and removing ChangeSets will need to happen on this shared thread or at least locks implemented around adding/removing ChangeSets, also every call to the transport adapter will have to happen from this thread too which means we'll need to make it more accessible to other classes.  

This is just from a simple analysis of the things the called method `scopeChanges` accesses and calls: https://github.com/uber/jetstream-ios/blob/develop/Jetstream/Session.swift#L153-L162

Also we'll need to clearly document that transport adapters will be called on this thread and that they should emit their signals for message received on a certain thread or create a way for observers to receive their changes on a certain thread.

We could potentially move absolutely everything into a background thread with the exception of the actual setting of properties on ModelObjects which we could use a helper to marshall back onto the main thread.  This would be a lot more work but ultimately probably necessary for high performance in the future.

**Comment by artman** [comment]
I'd probably want to take the loop count of the transaction test down rather than increase the other ones. Xcode will run these a number of times (10 or so?) and I found that having low loop counts actually are representative of the truth without slowing down the tests (make them do 10 times more and 6ms actually becomes 60ms).

What would actually make sense is to make all performance tests perform equally fast, eg. 100ms on specific target setup. That way you wouldn't have to remember the run speed of each individual test to be able to compare how code changes affect performance.

I naively didn't think about thread safety for Swift arrays, but yeah, quick google reveals that they're not thread safe. I'll try to create a test that covers this and then start working on a fix. I think this delivers the biggest bang for the buck, but going forward we should spend some time re-architecting everything from Scope onwards to get most of this moved off the main thread. Currently it's not possible since calling modify on the scope expects a ChangeSet back synchronously.

**Comment by robskillington** [comment]
I think making all performance tests almost equally as fast would be good for sure.

What are your thoughts on calling `client.transport.sendMessage(...)` from this thread as well?  Surely if you access any internals inside the transport adapter while in the context of this thread while your accessing the internals on another thread, say when you receive a message off the Websocket thread, there will be race conditions.  I don't think it would be great for anyone implementing transport adapters to always have to marshall themselves onto a shared thread and lock/unlock all their instance variables.  We should probably always call transport adapters methods from the same thread so they don't access their own instance variables in a non-thread safe manner.

**Comment by artman** [comment]
For sure, once the ChangeSet has been created, everything should happen on the serialQueue going outward. If incomming messages were queued up on the same serialQueue, too, then there would be only a few places where we'd have to synchronize access.

**Comment by artman** [comment]
Having a hard time creating a unit test that crashes. I would have thought that this would have done it, but no, runs fine:

       var callCount = 0
        
        // Make 100 changes
        for i in 0...100 {
            let changeSet = root.scope!.modify {
                self.root.integer = i
                self.child.integer = i
            }.observeCompletion(self) { error in
                callCount += 1
            }
        }
        
        client.session?.dispatchSerialSync {} // Wait serial queue to be empty
        
        // Queue up 100 more changes
        for i in 0...100 {
            let changeSet = root.scope!.modify {
                self.root.integer = i
                self.child.integer = i
            }
            // While changes are created and sent out, get get replies on the main queue
            var json: [String: AnyObject] = [
                "type": "ScopeSyncReply",
                "index": 2 + i,
                "replyTo": 1 + i,
                "fragmentReplies": [
                    [String: AnyObject](),
                    ["error": [
                        "type": "invalid-type",
                        "message": "Invalid type for property 'name'"
                        ]
                    ]
                ]
            ]
            var reply = ScopeSyncReplyMessage.unserialize(json)
            client.transport.messageReceived(reply!)
            
        }
        XCTAssertEqual(callCount, 100, "Did invoke completion block")

**Pull request closed without merging**
